import 'package:flight_app/constants/app_const.dart';
import 'package:flight_app/constants/img_api.dart';

class City {
  final String id;
  final String code;
  final String name;
  final String description;
  final List<String> photos;
  final double totalHotel;
  final double totalTransport;

  City({
    required this.id,
    required this.code,
    required this.name,
    required this.description,
    required this.photos,
    required this.totalHotel,
    required this.totalTransport,
  });
}

final List<City> cityList = [
  City(
    id: '1',
    code: 'LDN',
    name: 'London',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[1]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '2',
    code: 'LSB',
    name: 'Lisbon',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[2]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '3',
    code: 'PRS',
    name: 'Paris',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[16]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '4',
    code: 'KLP',
    name: 'Kuala Lumpur',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[4]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '5',
    code: 'IST',
    name: 'Istanbul',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[5]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '6',
    code: 'NEW',
    name: 'New York',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[24]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '7',
    code: 'DUB',
    name: 'Dubai',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[7]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '8',
    code: 'CAS',
    name: 'Casablanca',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[8]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '9',
    code: 'BEJ',
    name: 'Beijing',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[9]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '10',
    code: 'BAL',
    name: 'Bali',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[10]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '11',
    code: 'BNK',
    name: 'Bangkok',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[11]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '12',
    code: 'TKY',
    name: 'Tokyo',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[12]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '13',
    code: 'SNG',
    name: 'Singapore',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[19]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '14',
    code: 'BRL',
    name: 'Berlin',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[28]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '15',
    code: 'SNG',
    name: 'Singapore',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[15]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '16',
    code: 'LDN',
    name: 'London',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[3]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '17',
    code: 'NEW',
    name: 'New York',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[17]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '18',
    code: 'ROM',
    name: 'Rome',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[18]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '19',
    code: 'WAS',
    name: 'Washington',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[13]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '20',
    code: 'MMB',
    name: 'Mumbai',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[20]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '21',
    code: 'NDH',
    name: 'New Delhi',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[11]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '22',
    code: 'SEO',
    name: 'Seoul',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[22]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '23',
    code: 'SFC',
    name: 'San Francisco',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[23]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '24',
    code: 'DUB',
    name: 'Dubai',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[6]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '25',
    code: 'MDV',
    name: 'Maldives',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[25]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '26',
    code: 'VNC',
    name: 'Venice',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[26]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '27',
    code: 'MEC',
    name: 'Mecca',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[27]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '28',
    code: 'TKY',
    name: 'Tokyo',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[14]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '29',
    code: 'BUA',
    name: 'Buenos Aires',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[29]],
    totalHotel: 120,
    totalTransport: 50,
  ),
  City(
    id: '30',
    code: 'BDG',
    name: 'Bandung',
    description: ContentApi.paragraph,
    photos: [ImgApi.photo[30]],
    totalHotel: 120,
    totalTransport: 50,
  ),
];